vich_uploader:
    db_driver: orm

    mappings:
        recipes:
            uri_prefix: /upload/recipes
            upload_destination: '%kernel.project_dir%/public/upload/recipes'
        users:
            uri_prefix: /upload/users
            upload_destination: '%kernel.project_dir%/public/upload/users'
